services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"      # Redis-Port (für redis-om, redis-cli usw.)
      - "8001:8001"      # Web UI (optional, erreichbar auf http://localhost:8001)
    volumes:
      - ./redis-data:/data
    networks:
      - vyra-network
  vyra-kilted:
    build: .
    volumes:
      - .:/workspace/
    stdin_open: true
    # entrypoint: /ros_entrypoint.sh
    tty: true
    environment:
      - ROS_SECURITY_ENABLE=true
      - ROS_SECURITY_STRATEGY=Enforce
      - ROS_SECURITY_KEYSTORE=/workspace/sros2_keystore
    networks:
      - vyra-network
    command: bash -c "source /workspace/tools/update_ros.sh"
networks:
  vyra-network:
    external: true