services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"      # Redis-Port (für redis-om, redis-cli usw.)
      - "8001:8001"      # Web UI (optional, erreichbar auf http://localhost:8001)
    volumes:
      - ./redis-data:/data
  vyra-kilted:
    build: .
    volumes:
      - .:/workspace/
    stdin_open: true
    tty: true
