services:
  # redis:
  #   image: redis:7
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./redis-data:/data
  vyra-humble:
    build: ./vyra_module_template
    volumes:
      - ./vyra_module_template:/workspace/
    stdin_open: true
    tty: true
