package_name: vyra_module_template

module_access:
  level_4:
    username: "user"
    password: "user"
  level_5:
    username: "AdminVar"
    password: "Admin123"

lifecycle:
  auto_startup:
    enabled: true
    wait_sec_before_startup: 5
  
simulation:
  enabled: true
  simulation_name: "Vyra Simulation"
  simulation_description: "Simulation for Vyra Module Template"
  
development:
  enabled: true