# GetLogs.srv
# Request
int32 log_lines
uint8 log_level
---
# Response
vyra_module_interfaces/LoggerStream[] log_messages

# This service is used to retrieve logs from the V.Y.R.A. system.
# The log_lines field specifies the number of log lines to retrieve.
# The log_level field specifies the minimum log level to retrieve (e.g., INFO, WARNING, ERROR).
